AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LazyPhotoShare

  Sample SAM Template for LazyPhotoShare

Globals:
  Function:
    Timeout: 30

Resources:
  PhotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: PhotoFunction
      Handler: service.Handler::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment:
        Variables:
          REGION: ca-central-1
      Policies:
        - Statement:
            Effect: Allow
            Action:
                - secretsmanager:GetSecretValue
            Resource: '*'

  GooglePhotoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: GooglePhotoSecret
      SecretString: '{"clientId":"","clientSecret":"", "accessToken":"", "refreshToken":""}'
